### ISSUE TITLE
Compiler error when building COOL

### ISSUE THREAD

**Issue by Smigus** [rxwei/COOL#1]
When I built __COOL__ by running `make` under the `COOL` directory, I got two errors in the console log:

1. `'llvm-c/Analysis.h'` file not found
2. Could not build Objective-C module `LLVM_C`

For more detail, this is the complete console log:
```
swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib
Compile Swift Module 'CodeGen' (1 sources)
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "LLVM_C.h"
        ^
/Users/huangzhengcheng1/Developer/COOL/Packages/LLVM_C-1.0.0/LLVM_C.h:4:9: note: in file included from /Users/huangzhengcheng1/Developer/COOL/Packages/LLVM_C-1.0.0/LLVM_C.h:4:
#import "Analysis.h"
        ^
/Users/huangzhengcheng1/Developer/COOL/Packages/LLVM_C-1.0.0/Analysis.h:1:9: error: 'llvm-c/Analysis.h' file not found
#import <llvm-c/Analysis.h>
        ^
/Users/huangzhengcheng1/Developer/COOL/Sources/CodeGen/CodeGen.swift:11:8: error: could not build Objective-C module 'LLVM_C'
import LLVM_C.Core
       ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/huangzhengcheng1/Developer/COOL/.build/debug.yaml
make: *** [.build/debug/cool] Error 1
```

Also, when I built it on Xcode, Xcode tells me that there is no such module `LLVM_C.Core`, which I think simply results from the failure to build module `LLVM_C`.

As I understand, the failure to build module `LLVM_C` is simply the result of the first error. I tried to locate the `'llvm-c/Analysis.h'` file on my computer, and I found it in my `'/usr/local/Cellar/llvm/3.8.1/include'` directory. I added `'/usr/local/Cellar/llvm/3.8.1/bin'` to my `PATH` and built __COOL__ again, but the same error log appeared.

I now have no idea how to build it successfully.

**Comment by rxwei** [comment]
If you've installed LLVM using `brew`, you should be able to find LLVM C headers under `/usr/local/include/llvm-c/`. That's the header path specified in `Makefile`.
